In [2]:
#https://www.youtube.com/watch?v=-iQC0Fqpq70
#check this out it's funny

In [4]:
import pandas as pd
import numpy as np
import matplotlib as plt
import patsy
import statsmodels.api as sm
import scipy.stats as stats
from scipy.stats import ttest_ind, chisquare, normaltest
from datetime import datetime

In [5]:
df = pd.read_csv('ks-projects-201801.csv')

In [6]:
df

,Unnamed: 0,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,duration
0,0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11,0.00,failed,0,GB,0.00,0.00,1533.95,"59 days, 0:00:00"
1,1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02,2421.00,failed,15,US,100.00,2421.00,30000.00,"60 days, 0:00:00"
2,2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12,220.00,failed,3,US,220.00,220.00,45000.00,"45 days, 0:00:00"
3,3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17,1.00,failed,1,US,1.00,1.00,5000.00,"30 days, 0:00:00"
4,4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04,1283.00,canceled,14,US,1283.00,1283.00,19500.00,"56 days, 0:00:00"
5,5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26,52375.00,successful,224,US,52375.00,52375.00,50000.00,"35 days, 0:00:00"
6,6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01,1205.00,successful,16,US,1205.00,1205.00,1000.00,"20 days, 0:00:00"
7,7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01,453.00,failed,40,US,453.00,453.00,25000.00,"45 days, 0:00:00"
8,8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24,8233.00,canceled,58,US,8233.00,8233.00,125000.00,"35 days, 0:00:00"
9,9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11,6240.57,canceled,43,US,6240.57,6240.57,65000.00,"30 days, 0:00:00"
10,10,100004721,Of Jesus and Madmen,Nonfiction,Publishing,CAD,2013-10-09,2500.0,2013-09-09,0.00,failed,0,CA,0.00,0.00,2406.39,"30 days, 0:00:00"
11,11,100005484,Lisa Lim New CD!,Indie Rock,Music,USD,2013-04-08,12500.0,2013-03-09,12700.00,successful,100,US,12700.00,12700.00,12500.00,"30 days, 0:00:00"
12,12,1000055792,The Cottage Market,Crafts,Crafts,USD,2014-10-02,5000.0,2014-09-02,0.00,failed,0,US,0.00,0.00,5000.00,"30 days, 0:00:00"
13,13,1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,USD,2016-03-25,200000.0,2016-02-09,0.00,failed,0,US,0.00,0.00,200000.00,"45 days, 0:00:00"
14,14,1000057089,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,GBP,2017-05-03,5000.0,2017-04-05,94175.00,successful,761,GB,57763.78,121857.33,6469.73,"28 days, 0:00:00"
15,15,1000064368,Survival Rings,Design,Design,USD,2015-02-28,2500.0,2015-01-29,664.00,failed,11,US,664.00,664.00,2500.00,"30 days, 0:00:00"
16,16,1000064918,The Beard,Comic Books,Comics,USD,2014-11-08,1500.0,2014-10-09,395.00,failed,16,US,395.00,395.00,1500.00,"30 days, 0:00:00"
17,17,1000068480,Notes From London: Above & Below,Art Books,Publishing,USD,2015-05-10,3000.0,2015-04-10,789.00,failed,20,US,789.00,789.00,3000.00,"30 days, 0:00:00"
18,18,1000070642,Mike Corey's Darkness & Light Album,Music,Music,USD,2012-08-17,250.0,2012-08-02,250.00,successful,7,US,250.00,250.00,250.00,"15 days, 0:00:00"
19,19,1000071625,Boco Tea,Food,Food,USD,2012-06-02,5000.0,2012-05-03,1781.00,failed,40,US,1781.00,1781.00,5000.00,"30 days, 0:00:00"
20,20,1000072011,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,USD,2013-12-30,20000.0,2013-11-25,34268.00,successful,624,US,34268.00,34268.00,20000.00,"35 days, 0:00:00"
21,21,1000081649,MikeyJ clothing brand fundraiser,Childrenswear,Fashion,AUD,2017-09-07,2500.0,2017-08-08,1.00,failed,1,AU,0.00,0.81,2026.10,"30 days, 0:00:00"
22,22,1000082254,Alice in Wonderland in G Minor,Theater,Theater,USD,2014-06-15,3500.0,2014-05-16,650.00,failed,12,US,650.00,650.00,3500.00,"30 days, 0:00:00"
23,23,1000087442,Mountain brew: A quest for alcohol sustainability,Drinks,Food,NOK,2015-02-25,500.0,2015-01-26,48.00,failed,3,NO,6.18,6.29,65.55,"30 days, 0:00:00"
24,24,1000091520,The Book Zoo - A Mini-Comic,Comics,Comics,USD,2014-11-12,175.0,2014-10-23,701.66,successful,66,US,701.66,701.66,175.00,"20 days, 0:00:00"
25,25,1000102741,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,USD,2011-01-06,10000.0,2010-12-07,15827.00,successful,147,US,15827.00,15827.00,10000.00,"30 days, 0:00:00"
26,26,1000103948,Superhero Teddy Bear,DIY,Crafts,GBP,2016-01-05,12000.0,2015-12-06,0.00,failed,0,GB,0.00,0.00,17489.65,"30 days, 0:00:00"
27,27,1000104688,Permaculture Skills,Webseries,Film & Video,CAD,2014-12-14,17757.0,2014-11-14,48905.00,successful,571,CA,43203.25,42174.03,15313.04,"30 days, 0:00:00"
28,28,1000104953,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,GBP,2016-01-28,100.0,2015-12-29,112.38,successful,27,GB,167.70,160.60,142.91,"30 days, 0:00:00"
29,29,100011318,My Moon - Animated Short Film,Animation,Film & Video,USD,2017-05-03,50000.0,2017-04-03,57577.31,successful,840,US,10120.00,57577.31,50000.00,"30 days, 0:00:00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,2970,1015341816,Afraid of Dark,Documentary,Film & Video,USD,2014-05-09,15000.0,2014-04-09,16276.00,successful,198,US,16276.00,16276.00,15000.00,"30 days, 0:00:00"
2971,2971,1015351174,The Rovr Vest: A New Layer for Travel and Commute,Product Design,Design,USD,2017-01-02,8000.0,2016-12-09,3426.00,canceled,61,US,1769.00,3426.00,8000.00,"24 days, 0:00:00"
2972,2972,1015354341,Unimportant Conversations,Comics,Comics,USD,2012-04-30,1000.0,2012-03-31,136.00,failed,9,US,136.00,136.00,1000.00,"30 days, 0:00:00"
2973,2973,1015357412,The Ho Truth,Webseries,Film & Video,USD,2012-09-23,18000.0,2012-08-24,255.50,failed,19,US,255.50,255.50,18000.00,"30 days, 0:00:00"
2974,2974,1015357640,LITTLE DICK,Webseries,Film & Video,USD,2013-06-15,2500.0,2013-05-14,75.00,failed,3,US,75.00,75.00,2500.00,"32 days, 0:00:00"
2975,2975,1015362799,"LeCuir - Custom leather ipad/sling bag, iphone...",Product Design,Design,USD,2013-10-13,6000.0,2013-09-13,2449.00,canceled,26,US,2449.00,2449.00,6000.00,"30 days, 0:00:00"
2976,2976,1015365700,"VW ""Cult Generation"" poster. Fantastic origina...",Design,Design,EUR,2016-05-19,250.0,2016-04-19,29.00,failed,1,DE,32.72,32.53,280.47,"30 days, 0:00:00"
2977,2977,1015372493,Ego Trip project on DunaPart showcase,Performances,Dance,EUR,2015-01-16,1300.0,2014-12-17,1670.00,successful,36,NL,2080.22,1935.20,1506.44,"30 days, 0:00:00"
2978,2978,1015375165,THE PENGUIN COUNTERS Documentary Film,Documentary,Film & Video,USD,2013-10-10,50000.0,2013-09-09,55223.00,successful,351,US,55223.00,55223.00,50000.00,"31 days, 0:00:00"
2979,2979,1015381354,Krimson Titan Customs: Project Onyx (Canceled),3D Printing,Technology,USD,2015-09-05,1200.0,2015-08-06,0.00,canceled,0,US,0.00,0.00,1200.00,"30 days, 0:00:00"
2980,2980,1015385304,Make Me The Most Epic Adventurer of All Time (...,Comedy,Film & Video,USD,2014-10-03,50000.0,2014-09-03,1.00,failed,1,US,1.00,1.00,50000.00,"30 days, 0:00:00"
2981,2981,1015391940,Whose Serengeti?,Documentary,Film & Video,USD,2012-06-30,6500.0,2012-05-31,6510.00,successful,63,US,6510.00,6510.00,6500.00,"30 days, 0:00:00"
2982,2982,1015409774,SpinBlock Table Tennis Center,Games,Games,USD,2018-01-28,15000.0,2017-12-29,2445.00,live,30,US,1810.00,2445.00,15000.00,"30 days, 0:00:00"
2983,2983,1015413468,The Patch Whisky Project,Public Art,Art,USD,2013-03-19,3900.0,2013-02-25,4570.06,successful,66,US,4570.06,4570.06,3900.00,"22 days, 0:00:00"
2984,2984,1015417252,IF Anthology: CRIME published by Alterna Comics,Anthologies,Comics,USD,2017-10-02,1000.0,2017-09-21,4208.00,successful,161,US,169.00,4208.00,1000.00,"11 days, 0:00:00"
2985,2985,1015427142,Making a difference one step at a time by upcy...,Fashion,Fashion,USD,2014-03-15,5000.0,2014-02-13,90.00,failed,5,US,90.00,90.00,5000.00,"30 days, 0:00:00"
2986,2986,1015427647,"Seeding A ""Netcast""",Webseries,Film & Video,USD,2014-07-02,40000.0,2014-06-02,0.00,failed,0,US,0.00,0.00,40000.00,"30 days, 0:00:00"
2987,2987,1015429625,Waterless Glass Aquariums with 3D Printed Ocea...,3D Printing,Technology,USD,2016-03-16,75000.0,2016-02-16,2.00,failed,2,US,2.00,2.00,75000.00,"29 days, 0:00:00"
2988,2988,1015431039,Thirsting Sinner: Thirsty for Truth Hungry for...,Nonfiction,Publishing,USD,2012-03-13,5000.0,2012-02-12,0.00,failed,0,US,0.00,0.00,5000.00,"30 days, 0:00:00"
2989,2989,1015437901,Help Sebastian Plano release TWO NEW Albums !,Music,Music,USD,2012-08-21,10000.0,2012-07-17,10412.00,successful,244,US,10412.00,10412.00,10000.00,"35 days, 0:00:00"
2990,2990,1015442322,"Warner Robins Little Theatre Presents ""That Da...",Theater,Theater,USD,2014-03-16,2500.0,2014-01-15,610.00,failed,11,US,610.00,610.00,2500.00,"60 days, 0:00:00"
2991,2991,1015448692,Asteroid Artbook,Illustration,Art,EUR,2015-10-16,7500.0,2015-09-16,16694.00,successful,383,ES,18888.63,18964.42,8520.02,"30 days, 0:00:00"
2992,2992,1015459707,"My book is titled"" Daycare's Dirty Little Secr...",Nonfiction,Publishing,USD,2012-06-07,1500.0,2012-05-08,200.00,failed,6,US,200.00,200.00,1500.00,"30 days, 0:00:00"
2993,2993,1015466274,Genesis,Film & Video,Film & Video,EUR,2015-09-01,5000000.0,2015-07-07,0.00,failed,0,IT,0.00,0.00,5568982.99,"56 days, 0:00:00"
2994,2994,1015471596,Out Of Line Drawings,Illustration,Art,NOK,2017-12-13,10000.0,2017-10-14,0.00,canceled,0,NO,0.00,0.00,1206.81,"60 days, 0:00:00"
2995,2995,1015474687,Long Road,Film & Video,Film & Video,USD,2014-04-09,2200.0,2014-03-10,230.00,failed,7,US,230.00,230.00,2200.00,"30 days, 0:00:00"
2996,2996,10154884,"HALLE WANTS A JILT, FOR THE SECOND TIME",Pop,Music,USD,2012-07-16,8000.0,2012-06-02,8792.00,successful,98,US,8792.00,8792.00,8000.00,"44 days, 0:00:00"
2997,2997,1015500034,University thesis on social innovation (app cr...,Apps,Technology,EUR,2015-08-23,4000.0,2015-06-24,147.00,failed,27,IT,165.87,165.64,4507.19,"60 days, 0:00:00"
2998,2998,101550119,The Boy From Granite Falls book series,Fiction,Publishing,USD,2012-06-28,5000.0,2012-05-29,150.00,failed,1,US,150.00,150.00,5000.00,"30 days, 0:00:00"
2999,2999,1015511629,Regressia:album of Ukraine singer where Opera ...,Rock,Music,GBP,2014-03-29,1000.0,2014-01-28,63.00,failed,5,GB,103.94,104.40,1657.19,"60 days, 0:00:00"

In [7]:
#DATA CLEANING BEGINS HERE

#Some of the changes have been saved directly to the csv itself, altering the csv. This is because 
#    they take a really long time to load. They are commented out so you can see what we did, but it doesn't 
#    run every time.

In [8]:
df = df.head(3000)

In [9]:
def rt(date_t):
    date_t = date_t[:-9]
    return date_t
    # COMMENTING BECAUSE THIS IS ALREADY APPLIED TO THE CSV

In [10]:
#df["launched"] = df["launched"].apply(rt)
# COMMENTING BECAUSE THIS IS ALREADY APPLIED TO THE CSV

In [11]:
def makedt(start, end):
    start = datetime.strptime(str(start), '%Y-%m-%d')
    end = datetime.strptime(str(end), '%Y-%m-%d')
    return end - start
# COMMENTING BECAUSE THIS IS ALREADY APPLIED TO THE CSV

In [12]:
#df['duration'] = 'default' 
# COMMENTING BECAUSE THIS IS ALREADY APPLIED TO THE CSV
#df['duration'][i] = makedt(df['launched'][i], df['deadline'][i]) 
#for i in range(len(df)): 
#    df['duration'][i] = makedt(df['launched'][i], df['deadline'][i])

In [13]:
# COMMENTING BECAUSE THIS IS ALREADY APPLIED TO THE CSV 
#df.to_csv(r'ks-projects-201801.csv')

In [14]:
def clean_time(time):
    return time.split()[0]

In [15]:
df["duration"] = df["duration"].apply(clean_time)

In [16]:
df

,Unnamed: 0,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,duration
0,0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11,0.00,failed,0,GB,0.00,0.00,1533.95,59
1,1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02,2421.00,failed,15,US,100.00,2421.00,30000.00,60
2,2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12,220.00,failed,3,US,220.00,220.00,45000.00,45
3,3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17,1.00,failed,1,US,1.00,1.00,5000.00,30
4,4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04,1283.00,canceled,14,US,1283.00,1283.00,19500.00,56
5,5,1000014025,Monarch Espresso Bar,Restaurants,Food,USD,2016-04-01,50000.0,2016-02-26,52375.00,successful,224,US,52375.00,52375.00,50000.00,35
6,6,1000023410,Support Solar Roasted Coffee & Green Energy! ...,Food,Food,USD,2014-12-21,1000.0,2014-12-01,1205.00,successful,16,US,1205.00,1205.00,1000.00,20
7,7,1000030581,Chaser Strips. Our Strips make Shots their B*tch!,Drinks,Food,USD,2016-03-17,25000.0,2016-02-01,453.00,failed,40,US,453.00,453.00,25000.00,45
8,8,1000034518,SPIN - Premium Retractable In-Ear Headphones w...,Product Design,Design,USD,2014-05-29,125000.0,2014-04-24,8233.00,canceled,58,US,8233.00,8233.00,125000.00,35
9,9,100004195,STUDIO IN THE SKY - A Documentary Feature Film...,Documentary,Film & Video,USD,2014-08-10,65000.0,2014-07-11,6240.57,canceled,43,US,6240.57,6240.57,65000.00,30
10,10,100004721,Of Jesus and Madmen,Nonfiction,Publishing,CAD,2013-10-09,2500.0,2013-09-09,0.00,failed,0,CA,0.00,0.00,2406.39,30
11,11,100005484,Lisa Lim New CD!,Indie Rock,Music,USD,2013-04-08,12500.0,2013-03-09,12700.00,successful,100,US,12700.00,12700.00,12500.00,30
12,12,1000055792,The Cottage Market,Crafts,Crafts,USD,2014-10-02,5000.0,2014-09-02,0.00,failed,0,US,0.00,0.00,5000.00,30
13,13,1000056157,G-Spot Place for Gamers to connect with eachot...,Games,Games,USD,2016-03-25,200000.0,2016-02-09,0.00,failed,0,US,0.00,0.00,200000.00,45
14,14,1000057089,Tombstone: Old West tabletop game and miniatur...,Tabletop Games,Games,GBP,2017-05-03,5000.0,2017-04-05,94175.00,successful,761,GB,57763.78,121857.33,6469.73,28
15,15,1000064368,Survival Rings,Design,Design,USD,2015-02-28,2500.0,2015-01-29,664.00,failed,11,US,664.00,664.00,2500.00,30
16,16,1000064918,The Beard,Comic Books,Comics,USD,2014-11-08,1500.0,2014-10-09,395.00,failed,16,US,395.00,395.00,1500.00,30
17,17,1000068480,Notes From London: Above & Below,Art Books,Publishing,USD,2015-05-10,3000.0,2015-04-10,789.00,failed,20,US,789.00,789.00,3000.00,30
18,18,1000070642,Mike Corey's Darkness & Light Album,Music,Music,USD,2012-08-17,250.0,2012-08-02,250.00,successful,7,US,250.00,250.00,250.00,15
19,19,1000071625,Boco Tea,Food,Food,USD,2012-06-02,5000.0,2012-05-03,1781.00,failed,40,US,1781.00,1781.00,5000.00,30
20,20,1000072011,CMUK. Shoes: Take on Life Feet First.,Fashion,Fashion,USD,2013-12-30,20000.0,2013-11-25,34268.00,successful,624,US,34268.00,34268.00,20000.00,35
21,21,1000081649,MikeyJ clothing brand fundraiser,Childrenswear,Fashion,AUD,2017-09-07,2500.0,2017-08-08,1.00,failed,1,AU,0.00,0.81,2026.10,30
22,22,1000082254,Alice in Wonderland in G Minor,Theater,Theater,USD,2014-06-15,3500.0,2014-05-16,650.00,failed,12,US,650.00,650.00,3500.00,30
23,23,1000087442,Mountain brew: A quest for alcohol sustainability,Drinks,Food,NOK,2015-02-25,500.0,2015-01-26,48.00,failed,3,NO,6.18,6.29,65.55,30
24,24,1000091520,The Book Zoo - A Mini-Comic,Comics,Comics,USD,2014-11-12,175.0,2014-10-23,701.66,successful,66,US,701.66,701.66,175.00,20
25,25,1000102741,Matt Cavenaugh & Jenny Powers make their 1st a...,Music,Music,USD,2011-01-06,10000.0,2010-12-07,15827.00,successful,147,US,15827.00,15827.00,10000.00,30
26,26,1000103948,Superhero Teddy Bear,DIY,Crafts,GBP,2016-01-05,12000.0,2015-12-06,0.00,failed,0,GB,0.00,0.00,17489.65,30
27,27,1000104688,Permaculture Skills,Webseries,Film & Video,CAD,2014-12-14,17757.0,2014-11-14,48905.00,successful,571,CA,43203.25,42174.03,15313.04,30
28,28,1000104953,Rebel Army Origins: The Heroic Story Of Major ...,Comics,Comics,GBP,2016-01-28,100.0,2015-12-29,112.38,successful,27,GB,167.70,160.60,142.91,30
29,29,100011318,My Moon - Animated Short Film,Animation,Film & Video,USD,2017-05-03,50000.0,2017-04-03,57577.31,successful,840,US,10120.00,57577.31,50000.00,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,2970,1015341816,Afraid of Dark,Documentary,Film & Video,USD,2014-05-09,15000.0,2014-04-09,16276.00,successful,198,US,16276.00,16276.00,15000.00,30
2971,2971,1015351174,The Rovr Vest: A New Layer for Travel and Commute,Product Design,Design,USD,2017-01-02,8000.0,2016-12-09,3426.00,canceled,61,US,1769.00,3426.00,8000.00,24
2972,2972,1015354341,Unimportant Conversations,Comics,Comics,USD,2012-04-30,1000.0,2012-03-31,136.00,failed,9,US,136.00,136.00,1000.00,30
2973,2973,1015357412,The Ho Truth,Webseries,Film & Video,USD,2012-09-23,18000.0,2012-08-24,255.50,failed,19,US,255.50,255.50,18000.00,30
2974,2974,1015357640,LITTLE DICK,Webseries,Film & Video,USD,2013-06-15,2500.0,2013-05-14,75.00,failed,3,US,75.00,75.00,2500.00,32
2975,2975,1015362799,"LeCuir - Custom leather ipad/sling bag, iphone...",Product Design,Design,USD,2013-10-13,6000.0,2013-09-13,2449.00,canceled,26,US,2449.00,2449.00,6000.00,30
2976,2976,1015365700,"VW ""Cult Generation"" poster. Fantastic origina...",Design,Design,EUR,2016-05-19,250.0,2016-04-19,29.00,failed,1,DE,32.72,32.53,280.47,30
2977,2977,1015372493,Ego Trip project on DunaPart showcase,Performances,Dance,EUR,2015-01-16,1300.0,2014-12-17,1670.00,successful,36,NL,2080.22,1935.20,1506.44,30
2978,2978,1015375165,THE PENGUIN COUNTERS Documentary Film,Documentary,Film & Video,USD,2013-10-10,50000.0,2013-09-09,55223.00,successful,351,US,55223.00,55223.00,50000.00,31
2979,2979,1015381354,Krimson Titan Customs: Project Onyx (Canceled),3D Printing,Technology,USD,2015-09-05,1200.0,2015-08-06,0.00,canceled,0,US,0.00,0.00,1200.00,30
2980,2980,1015385304,Make Me The Most Epic Adventurer of All Time (...,Comedy,Film & Video,USD,2014-10-03,50000.0,2014-09-03,1.00,failed,1,US,1.00,1.00,50000.00,30
2981,2981,1015391940,Whose Serengeti?,Documentary,Film & Video,USD,2012-06-30,6500.0,2012-05-31,6510.00,successful,63,US,6510.00,6510.00,6500.00,30
2982,2982,1015409774,SpinBlock Table Tennis Center,Games,Games,USD,2018-01-28,15000.0,2017-12-29,2445.00,live,30,US,1810.00,2445.00,15000.00,30
2983,2983,1015413468,The Patch Whisky Project,Public Art,Art,USD,2013-03-19,3900.0,2013-02-25,4570.06,successful,66,US,4570.06,4570.06,3900.00,22
2984,2984,1015417252,IF Anthology: CRIME published by Alterna Comics,Anthologies,Comics,USD,2017-10-02,1000.0,2017-09-21,4208.00,successful,161,US,169.00,4208.00,1000.00,11
2985,2985,1015427142,Making a difference one step at a time by upcy...,Fashion,Fashion,USD,2014-03-15,5000.0,2014-02-13,90.00,failed,5,US,90.00,90.00,5000.00,30
2986,2986,1015427647,"Seeding A ""Netcast""",Webseries,Film & Video,USD,2014-07-02,40000.0,2014-06-02,0.00,failed,0,US,0.00,0.00,40000.00,30
2987,2987,1015429625,Waterless Glass Aquariums with 3D Printed Ocea...,3D Printing,Technology,USD,2016-03-16,75000.0,2016-02-16,2.00,failed,2,US,2.00,2.00,75000.00,29
2988,2988,1015431039,Thirsting Sinner: Thirsty for Truth Hungry for...,Nonfiction,Publishing,USD,2012-03-13,5000.0,2012-02-12,0.00,failed,0,US,0.00,0.00,5000.00,30
2989,2989,1015437901,Help Sebastian Plano release TWO NEW Albums !,Music,Music,USD,2012-08-21,10000.0,2012-07-17,10412.00,successful,244,US,10412.00,10412.00,10000.00,35
2990,2990,1015442322,"Warner Robins Little Theatre Presents ""That Da...",Theater,Theater,USD,2014-03-16,2500.0,2014-01-15,610.00,failed,11,US,610.00,610.00,2500.00,60
2991,2991,1015448692,Asteroid Artbook,Illustration,Art,EUR,2015-10-16,7500.0,2015-09-16,16694.00,successful,383,ES,18888.63,18964.42,8520.02,30
2992,2992,1015459707,"My book is titled"" Daycare's Dirty Little Secr...",Nonfiction,Publishing,USD,2012-06-07,1500.0,2012-05-08,200.00,failed,6,US,200.00,200.00,1500.00,30
2993,2993,1015466274,Genesis,Film & Video,Film & Video,EUR,2015-09-01,5000000.0,2015-07-07,0.00,failed,0,IT,0.00,0.00,5568982.99,56
2994,2994,1015471596,Out Of Line Drawings,Illustration,Art,NOK,2017-12-13,10000.0,2017-10-14,0.00,canceled,0,NO,0.00,0.00,1206.81,60
2995,2995,1015474687,Long Road,Film & Video,Film & Video,USD,2014-04-09,2200.0,2014-03-10,230.00,failed,7,US,230.00,230.00,2200.00,30
2996,2996,10154884,"HALLE WANTS A JILT, FOR THE SECOND TIME",Pop,Music,USD,2012-07-16,8000.0,2012-06-02,8792.00,successful,98,US,8792.00,8792.00,8000.00,44
2997,2997,1015500034,University thesis on social innovation (app cr...,Apps,Technology,EUR,2015-08-23,4000.0,2015-06-24,147.00,failed,27,IT,165.87,165.64,4507.19,60
2998,2998,101550119,The Boy From Granite Falls book series,Fiction,Publishing,USD,2012-06-28,5000.0,2012-05-29,150.00,failed,1,US,150.00,150.00,5000.00,30
2999,2999,1015511629,Regressia:album of Ukraine singer where Opera ...,Rock,Music,GBP,2014-03-29,1000.0,2014-01-28,63.00,failed,5,GB,103.94,104.40,1657.19,60

In [17]:
#remove columns name, country, category, backers, goal, and pledged
# we remove backers because that is only known after the fact, and we want to be able to predict success of a campaign
# we will use usd_goal_real and usd_pledged_real because the conversions have already been done to USD for these

In [18]:
df = df.drop(['name', 'country', 'category', 'backers', 'goal', 'pledged', 'usd pledged','currency'], axis=1)

In [19]:
df.head()

,Unnamed: 0,ID,main_category,deadline,launched,state,usd_pledged_real,usd_goal_real,duration
0,0,1000002330,Publishing,2015-10-09,2015-08-11,failed,0.0,1533.95,59
1,1,1000003930,Film & Video,2017-11-01,2017-09-02,failed,2421.0,30000.00,60
2,2,1000004038,Film & Video,2013-02-26,2013-01-12,failed,220.0,45000.00,45
3,3,1000007540,Music,2012-04-16,2012-03-17,failed,1.0,5000.00,30
4,4,1000011046,Film & Video,2015-08-29,2015-07-04,canceled,1283.0,19500.00,56

In [20]:
#rename columns for simplicity
#note that we are using names that previously meant similar things but were not as useful; don't be confused.
df.rename(columns={'usd_pledged_real':'pledged',
                          'usd_goal_real':'goal',
                          'main_category': 'category'
                          'Unnamed'}, inplace = True)
df

,Unnamed: 0,ID,categoryUnnamed,deadline,launched,state,pledged,goal,duration
0,0,1000002330,Publishing,2015-10-09,2015-08-11,failed,0.00,1533.95,59
1,1,1000003930,Film & Video,2017-11-01,2017-09-02,failed,2421.00,30000.00,60
2,2,1000004038,Film & Video,2013-02-26,2013-01-12,failed,220.00,45000.00,45
3,3,1000007540,Music,2012-04-16,2012-03-17,failed,1.00,5000.00,30
4,4,1000011046,Film & Video,2015-08-29,2015-07-04,canceled,1283.00,19500.00,56
5,5,1000014025,Food,2016-04-01,2016-02-26,successful,52375.00,50000.00,35
6,6,1000023410,Food,2014-12-21,2014-12-01,successful,1205.00,1000.00,20
7,7,1000030581,Food,2016-03-17,2016-02-01,failed,453.00,25000.00,45
8,8,1000034518,Design,2014-05-29,2014-04-24,canceled,8233.00,125000.00,35
9,9,100004195,Film & Video,2014-08-10,2014-07-11,canceled,6240.57,65000.00,30
10,10,100004721,Publishing,2013-10-09,2013-09-09,failed,0.00,2406.39,30
11,11,100005484,Music,2013-04-08,2013-03-09,successful,12700.00,12500.00,30
12,12,1000055792,Crafts,2014-10-02,2014-09-02,failed,0.00,5000.00,30
13,13,1000056157,Games,2016-03-25,2016-02-09,failed,0.00,200000.00,45
14,14,1000057089,Games,2017-05-03,2017-04-05,successful,121857.33,6469.73,28
15,15,1000064368,Design,2015-02-28,2015-01-29,failed,664.00,2500.00,30
16,16,1000064918,Comics,2014-11-08,2014-10-09,failed,395.00,1500.00,30
17,17,1000068480,Publishing,2015-05-10,2015-04-10,failed,789.00,3000.00,30
18,18,1000070642,Music,2012-08-17,2012-08-02,successful,250.00,250.00,15
19,19,1000071625,Food,2012-06-02,2012-05-03,failed,1781.00,5000.00,30
20,20,1000072011,Fashion,2013-12-30,2013-11-25,successful,34268.00,20000.00,35
21,21,1000081649,Fashion,2017-09-07,2017-08-08,failed,0.81,2026.10,30
22,22,1000082254,Theater,2014-06-15,2014-05-16,failed,650.00,3500.00,30
23,23,1000087442,Food,2015-02-25,2015-01-26,failed,6.29,65.55,30
24,24,1000091520,Comics,2014-11-12,2014-10-23,successful,701.66,175.00,20
25,25,1000102741,Music,2011-01-06,2010-12-07,successful,15827.00,10000.00,30
26,26,1000103948,Crafts,2016-01-05,2015-12-06,failed,0.00,17489.65,30
27,27,1000104688,Film & Video,2014-12-14,2014-11-14,successful,42174.03,15313.04,30
28,28,1000104953,Comics,2016-01-28,2015-12-29,successful,160.60,142.91,30
29,29,100011318,Film & Video,2017-05-03,2017-04-03,successful,57577.31,50000.00,30
...,...,...,...,...,...,...,...,...,...
2970,2970,1015341816,Film & Video,2014-05-09,2014-04-09,successful,16276.00,15000.00,30
2971,2971,1015351174,Design,2017-01-02,2016-12-09,canceled,3426.00,8000.00,24
2972,2972,1015354341,Comics,2012-04-30,2012-03-31,failed,136.00,1000.00,30
2973,2973,1015357412,Film & Video,2012-09-23,2012-08-24,failed,255.50,18000.00,30
2974,2974,1015357640,Film & Video,2013-06-15,2013-05-14,failed,75.00,2500.00,32
2975,2975,1015362799,Design,2013-10-13,2013-09-13,canceled,2449.00,6000.00,30
2976,2976,1015365700,Design,2016-05-19,2016-04-19,failed,32.53,280.47,30
2977,2977,1015372493,Dance,2015-01-16,2014-12-17,successful,1935.20,1506.44,30
2978,2978,1015375165,Film & Video,2013-10-10,2013-09-09,successful,55223.00,50000.00,31
2979,2979,1015381354,Technology,2015-09-05,2015-08-06,canceled,0.00,1200.00,30
2980,2980,1015385304,Film & Video,2014-10-03,2014-09-03,failed,1.00,50000.00,30
2981,2981,1015391940,Film & Video,2012-06-30,2012-05-31,successful,6510.00,6500.00,30
2982,2982,1015409774,Games,2018-01-28,2017-12-29,live,2445.00,15000.00,30
2983,2983,1015413468,Art,2013-03-19,2013-02-25,successful,4570.06,3900.00,22
2984,2984,1015417252,Comics,2017-10-02,2017-09-21,successful,4208.00,1000.00,11
2985,2985,1015427142,Fashion,2014-03-15,2014-02-13,failed,90.00,5000.00,30
2986,2986,1015427647,Film & Video,2014-07-02,2014-06-02,failed,0.00,40000.00,30
2987,2987,1015429625,Technology,2016-03-16,2016-02-16,failed,2.00,75000.00,29
2988,2988,1015431039,Publishing,2012-03-13,2012-02-12,failed,0.00,5000.00,30
2989,2989,1015437901,Music,2012-08-21,2012-07-17,successful,10412.00,10000.00,35
2990,2990,1015442322,Theater,2014-03-16,2014-01-15,failed,610.00,2500.00,60
2991,2991,1015448692,Art,2015-10-16,2015-09-16,successful,18964.42,8520.02,30
2992,2992,1015459707,Publishing,2012-06-07,2012-05-08,failed,200.00,1500.00,30
2993,2993,1015466274,Film & Video,2015-09-01,2015-07-07,failed,0.00,5568982.99,56
2994,2994,1015471596,Art,2017-12-13,2017-10-14,canceled,0.00,1206.81,60
2995,2995,1015474687,Film & Video,2014-04-09,2014-03-10,failed,230.00,2200.00,30
2996,2996,10154884,Music,2012-07-16,2012-06-02,successful,8792.00,8000.00,44
2997,2997,1015500034,Technology,2015-08-23,2015-06-24,failed,165.64,4507.19,60
2998,2998,101550119,Publishing,2012-06-28,2012-05-29,failed,150.00,5000.00,30
2999,2999,1015511629,Music,2014-03-29,2014-01-28,failed,104.40,1657.19,60

In [46]:
df.state.unique()

array(['failed', 'successful'], dtype=object)

In [40]:
#remove rows with states other than successful, failed, or cancel, and change canceled to failed
df = df.drop(df[df.state == 'live'].index)
df = df.drop(df[df.state == 'undefined'].index)
df = df.drop(df[df.state == 'suspended'].index)

In [38]:
df

,Unnamed: 0,ID,categoryUnnamed,deadline,launched,state,pledged,goal,duration
0,0,1000002330,Publishing,2015-10-09,2015-08-11,failed,0.00,1533.95,59
1,1,1000003930,Film & Video,2017-11-01,2017-09-02,failed,2421.00,30000.00,60
2,2,1000004038,Film & Video,2013-02-26,2013-01-12,failed,220.00,45000.00,45
3,3,1000007540,Music,2012-04-16,2012-03-17,failed,1.00,5000.00,30
4,4,1000011046,Film & Video,2015-08-29,2015-07-04,canceled,1283.00,19500.00,56
5,5,1000014025,Food,2016-04-01,2016-02-26,successful,52375.00,50000.00,35
6,6,1000023410,Food,2014-12-21,2014-12-01,successful,1205.00,1000.00,20
7,7,1000030581,Food,2016-03-17,2016-02-01,failed,453.00,25000.00,45
8,8,1000034518,Design,2014-05-29,2014-04-24,canceled,8233.00,125000.00,35
9,9,100004195,Film & Video,2014-08-10,2014-07-11,canceled,6240.57,65000.00,30
10,10,100004721,Publishing,2013-10-09,2013-09-09,failed,0.00,2406.39,30
11,11,100005484,Music,2013-04-08,2013-03-09,successful,12700.00,12500.00,30
12,12,1000055792,Crafts,2014-10-02,2014-09-02,failed,0.00,5000.00,30
13,13,1000056157,Games,2016-03-25,2016-02-09,failed,0.00,200000.00,45
14,14,1000057089,Games,2017-05-03,2017-04-05,successful,121857.33,6469.73,28
15,15,1000064368,Design,2015-02-28,2015-01-29,failed,664.00,2500.00,30
16,16,1000064918,Comics,2014-11-08,2014-10-09,failed,395.00,1500.00,30
17,17,1000068480,Publishing,2015-05-10,2015-04-10,failed,789.00,3000.00,30
18,18,1000070642,Music,2012-08-17,2012-08-02,successful,250.00,250.00,15
19,19,1000071625,Food,2012-06-02,2012-05-03,failed,1781.00,5000.00,30
20,20,1000072011,Fashion,2013-12-30,2013-11-25,successful,34268.00,20000.00,35
21,21,1000081649,Fashion,2017-09-07,2017-08-08,failed,0.81,2026.10,30
22,22,1000082254,Theater,2014-06-15,2014-05-16,failed,650.00,3500.00,30
23,23,1000087442,Food,2015-02-25,2015-01-26,failed,6.29,65.55,30
24,24,1000091520,Comics,2014-11-12,2014-10-23,successful,701.66,175.00,20
25,25,1000102741,Music,2011-01-06,2010-12-07,successful,15827.00,10000.00,30
26,26,1000103948,Crafts,2016-01-05,2015-12-06,failed,0.00,17489.65,30
27,27,1000104688,Film & Video,2014-12-14,2014-11-14,successful,42174.03,15313.04,30
28,28,1000104953,Comics,2016-01-28,2015-12-29,successful,160.60,142.91,30
29,29,100011318,Film & Video,2017-05-03,2017-04-03,successful,57577.31,50000.00,30
...,...,...,...,...,...,...,...,...,...
2969,2969,101534073,Technology,2015-05-04,2015-03-30,failed,806.00,50000.00,35
2970,2970,1015341816,Film & Video,2014-05-09,2014-04-09,successful,16276.00,15000.00,30
2971,2971,1015351174,Design,2017-01-02,2016-12-09,canceled,3426.00,8000.00,24
2972,2972,1015354341,Comics,2012-04-30,2012-03-31,failed,136.00,1000.00,30
2973,2973,1015357412,Film & Video,2012-09-23,2012-08-24,failed,255.50,18000.00,30
2974,2974,1015357640,Film & Video,2013-06-15,2013-05-14,failed,75.00,2500.00,32
2975,2975,1015362799,Design,2013-10-13,2013-09-13,canceled,2449.00,6000.00,30
2976,2976,1015365700,Design,2016-05-19,2016-04-19,failed,32.53,280.47,30
2977,2977,1015372493,Dance,2015-01-16,2014-12-17,successful,1935.20,1506.44,30
2978,2978,1015375165,Film & Video,2013-10-10,2013-09-09,successful,55223.00,50000.00,31
2979,2979,1015381354,Technology,2015-09-05,2015-08-06,canceled,0.00,1200.00,30
2980,2980,1015385304,Film & Video,2014-10-03,2014-09-03,failed,1.00,50000.00,30
2981,2981,1015391940,Film & Video,2012-06-30,2012-05-31,successful,6510.00,6500.00,30
2983,2983,1015413468,Art,2013-03-19,2013-02-25,successful,4570.06,3900.00,22
2984,2984,1015417252,Comics,2017-10-02,2017-09-21,successful,4208.00,1000.00,11
2985,2985,1015427142,Fashion,2014-03-15,2014-02-13,failed,90.00,5000.00,30
2986,2986,1015427647,Film & Video,2014-07-02,2014-06-02,failed,0.00,40000.00,30
2987,2987,1015429625,Technology,2016-03-16,2016-02-16,failed,2.00,75000.00,29
2988,2988,1015431039,Publishing,2012-03-13,2012-02-12,failed,0.00,5000.00,30
2989,2989,1015437901,Music,2012-08-21,2012-07-17,successful,10412.00,10000.00,35
2990,2990,1015442322,Theater,2014-03-16,2014-01-15,failed,610.00,2500.00,60
2991,2991,1015448692,Art,2015-10-16,2015-09-16,successful,18964.42,8520.02,30
2992,2992,1015459707,Publishing,2012-06-07,2012-05-08,failed,200.00,1500.00,30
2993,2993,1015466274,Film & Video,2015-09-01,2015-07-07,failed,0.00,5568982.99,56
2994,2994,1015471596,Art,2017-12-13,2017-10-14,canceled,0.00,1206.81,60
2995,2995,1015474687,Film & Video,2014-04-09,2014-03-10,failed,230.00,2200.00,30
2996,2996,10154884,Music,2012-07-16,2012-06-02,successful,8792.00,8000.00,44
2997,2997,1015500034,Technology,2015-08-23,2015-06-24,failed,165.64,4507.19,60
2998,2998,101550119,Publishing,2012-06-28,2012-05-29,failed,150.00,5000.00,30
2999,2999,1015511629,Music,2014-03-29,2014-01-28,failed,104.40,1657.19,60

In [42]:
def cancel_to_fail(state):
    if state == 'canceled':
        state = 'failed'
    return state

In [45]:
df['state'] = df['state'].apply(cancel_to_fail)
df

,Unnamed: 0,ID,categoryUnnamed,deadline,launched,state,pledged,goal,duration
0,0,1000002330,Publishing,2015-10-09,2015-08-11,failed,0.00,1533.95,59
1,1,1000003930,Film & Video,2017-11-01,2017-09-02,failed,2421.00,30000.00,60
2,2,1000004038,Film & Video,2013-02-26,2013-01-12,failed,220.00,45000.00,45
3,3,1000007540,Music,2012-04-16,2012-03-17,failed,1.00,5000.00,30
4,4,1000011046,Film & Video,2015-08-29,2015-07-04,failed,1283.00,19500.00,56
5,5,1000014025,Food,2016-04-01,2016-02-26,successful,52375.00,50000.00,35
6,6,1000023410,Food,2014-12-21,2014-12-01,successful,1205.00,1000.00,20
7,7,1000030581,Food,2016-03-17,2016-02-01,failed,453.00,25000.00,45
8,8,1000034518,Design,2014-05-29,2014-04-24,failed,8233.00,125000.00,35
9,9,100004195,Film & Video,2014-08-10,2014-07-11,failed,6240.57,65000.00,30
10,10,100004721,Publishing,2013-10-09,2013-09-09,failed,0.00,2406.39,30
11,11,100005484,Music,2013-04-08,2013-03-09,successful,12700.00,12500.00,30
12,12,1000055792,Crafts,2014-10-02,2014-09-02,failed,0.00,5000.00,30
13,13,1000056157,Games,2016-03-25,2016-02-09,failed,0.00,200000.00,45
14,14,1000057089,Games,2017-05-03,2017-04-05,successful,121857.33,6469.73,28
15,15,1000064368,Design,2015-02-28,2015-01-29,failed,664.00,2500.00,30
16,16,1000064918,Comics,2014-11-08,2014-10-09,failed,395.00,1500.00,30
17,17,1000068480,Publishing,2015-05-10,2015-04-10,failed,789.00,3000.00,30
18,18,1000070642,Music,2012-08-17,2012-08-02,successful,250.00,250.00,15
19,19,1000071625,Food,2012-06-02,2012-05-03,failed,1781.00,5000.00,30
20,20,1000072011,Fashion,2013-12-30,2013-11-25,successful,34268.00,20000.00,35
21,21,1000081649,Fashion,2017-09-07,2017-08-08,failed,0.81,2026.10,30
22,22,1000082254,Theater,2014-06-15,2014-05-16,failed,650.00,3500.00,30
23,23,1000087442,Food,2015-02-25,2015-01-26,failed,6.29,65.55,30
24,24,1000091520,Comics,2014-11-12,2014-10-23,successful,701.66,175.00,20
25,25,1000102741,Music,2011-01-06,2010-12-07,successful,15827.00,10000.00,30
26,26,1000103948,Crafts,2016-01-05,2015-12-06,failed,0.00,17489.65,30
27,27,1000104688,Film & Video,2014-12-14,2014-11-14,successful,42174.03,15313.04,30
28,28,1000104953,Comics,2016-01-28,2015-12-29,successful,160.60,142.91,30
29,29,100011318,Film & Video,2017-05-03,2017-04-03,successful,57577.31,50000.00,30
...,...,...,...,...,...,...,...,...,...
2969,2969,101534073,Technology,2015-05-04,2015-03-30,failed,806.00,50000.00,35
2970,2970,1015341816,Film & Video,2014-05-09,2014-04-09,successful,16276.00,15000.00,30
2971,2971,1015351174,Design,2017-01-02,2016-12-09,failed,3426.00,8000.00,24
2972,2972,1015354341,Comics,2012-04-30,2012-03-31,failed,136.00,1000.00,30
2973,2973,1015357412,Film & Video,2012-09-23,2012-08-24,failed,255.50,18000.00,30
2974,2974,1015357640,Film & Video,2013-06-15,2013-05-14,failed,75.00,2500.00,32
2975,2975,1015362799,Design,2013-10-13,2013-09-13,failed,2449.00,6000.00,30
2976,2976,1015365700,Design,2016-05-19,2016-04-19,failed,32.53,280.47,30
2977,2977,1015372493,Dance,2015-01-16,2014-12-17,successful,1935.20,1506.44,30
2978,2978,1015375165,Film & Video,2013-10-10,2013-09-09,successful,55223.00,50000.00,31
2979,2979,1015381354,Technology,2015-09-05,2015-08-06,failed,0.00,1200.00,30
2980,2980,1015385304,Film & Video,2014-10-03,2014-09-03,failed,1.00,50000.00,30
2981,2981,1015391940,Film & Video,2012-06-30,2012-05-31,successful,6510.00,6500.00,30
2983,2983,1015413468,Art,2013-03-19,2013-02-25,successful,4570.06,3900.00,22
2984,2984,1015417252,Comics,2017-10-02,2017-09-21,successful,4208.00,1000.00,11
2985,2985,1015427142,Fashion,2014-03-15,2014-02-13,failed,90.00,5000.00,30
2986,2986,1015427647,Film & Video,2014-07-02,2014-06-02,failed,0.00,40000.00,30
2987,2987,1015429625,Technology,2016-03-16,2016-02-16,failed,2.00,75000.00,29
2988,2988,1015431039,Publishing,2012-03-13,2012-02-12,failed,0.00,5000.00,30
2989,2989,1015437901,Music,2012-08-21,2012-07-17,successful,10412.00,10000.00,35
2990,2990,1015442322,Theater,2014-03-16,2014-01-15,failed,610.00,2500.00,60
2991,2991,1015448692,Art,2015-10-16,2015-09-16,successful,18964.42,8520.02,30
2992,2992,1015459707,Publishing,2012-06-07,2012-05-08,failed,200.00,1500.00,30
2993,2993,1015466274,Film & Video,2015-09-01,2015-07-07,failed,0.00,5568982.99,56
2994,2994,1015471596,Art,2017-12-13,2017-10-14,failed,0.00,1206.81,60
2995,2995,1015474687,Film & Video,2014-04-09,2014-03-10,failed,230.00,2200.00,30
2996,2996,10154884,Music,2012-07-16,2012-06-02,successful,8792.00,8000.00,44
2997,2997,1015500034,Technology,2015-08-23,2015-06-24,failed,165.64,4507.19,60
2998,2998,101550119,Publishing,2012-06-28,2012-05-29,failed,150.00,5000.00,30
2999,2999,1015511629,Music,2014-03-29,2014-01-28,failed,104.40,1657.19,60

In [22]:
#END DATA CLEANING

In [24]:
#let's do a linear model to predict success/fail based on category, (not yet)duration, and goal
#outcome, predictors = patsy.dmatrices('state ~ category + goal', df)
#mod = sm.OLS(outcome, predictors)
#res = mod.fit()

In [25]:
#res.summary()

In [26]:
df

,Unnamed: 0,ID,categoryUnnamed,deadline,launched,state,pledged,goal,duration
0,0,1000002330,Publishing,2015-10-09,2015-08-11,failed,0.00,1533.95,59
1,1,1000003930,Film & Video,2017-11-01,2017-09-02,failed,2421.00,30000.00,60
2,2,1000004038,Film & Video,2013-02-26,2013-01-12,failed,220.00,45000.00,45
3,3,1000007540,Music,2012-04-16,2012-03-17,failed,1.00,5000.00,30
4,4,1000011046,Film & Video,2015-08-29,2015-07-04,canceled,1283.00,19500.00,56
5,5,1000014025,Food,2016-04-01,2016-02-26,successful,52375.00,50000.00,35
6,6,1000023410,Food,2014-12-21,2014-12-01,successful,1205.00,1000.00,20
7,7,1000030581,Food,2016-03-17,2016-02-01,failed,453.00,25000.00,45
8,8,1000034518,Design,2014-05-29,2014-04-24,canceled,8233.00,125000.00,35
9,9,100004195,Film & Video,2014-08-10,2014-07-11,canceled,6240.57,65000.00,30
10,10,100004721,Publishing,2013-10-09,2013-09-09,failed,0.00,2406.39,30
11,11,100005484,Music,2013-04-08,2013-03-09,successful,12700.00,12500.00,30
12,12,1000055792,Crafts,2014-10-02,2014-09-02,failed,0.00,5000.00,30
13,13,1000056157,Games,2016-03-25,2016-02-09,failed,0.00,200000.00,45
14,14,1000057089,Games,2017-05-03,2017-04-05,successful,121857.33,6469.73,28
15,15,1000064368,Design,2015-02-28,2015-01-29,failed,664.00,2500.00,30
16,16,1000064918,Comics,2014-11-08,2014-10-09,failed,395.00,1500.00,30
17,17,1000068480,Publishing,2015-05-10,2015-04-10,failed,789.00,3000.00,30
18,18,1000070642,Music,2012-08-17,2012-08-02,successful,250.00,250.00,15
19,19,1000071625,Food,2012-06-02,2012-05-03,failed,1781.00,5000.00,30
20,20,1000072011,Fashion,2013-12-30,2013-11-25,successful,34268.00,20000.00,35
21,21,1000081649,Fashion,2017-09-07,2017-08-08,failed,0.81,2026.10,30
22,22,1000082254,Theater,2014-06-15,2014-05-16,failed,650.00,3500.00,30
23,23,1000087442,Food,2015-02-25,2015-01-26,failed,6.29,65.55,30
24,24,1000091520,Comics,2014-11-12,2014-10-23,successful,701.66,175.00,20
25,25,1000102741,Music,2011-01-06,2010-12-07,successful,15827.00,10000.00,30
26,26,1000103948,Crafts,2016-01-05,2015-12-06,failed,0.00,17489.65,30
27,27,1000104688,Film & Video,2014-12-14,2014-11-14,successful,42174.03,15313.04,30
28,28,1000104953,Comics,2016-01-28,2015-12-29,successful,160.60,142.91,30
29,29,100011318,Film & Video,2017-05-03,2017-04-03,successful,57577.31,50000.00,30
...,...,...,...,...,...,...,...,...,...
2970,2970,1015341816,Film & Video,2014-05-09,2014-04-09,successful,16276.00,15000.00,30
2971,2971,1015351174,Design,2017-01-02,2016-12-09,canceled,3426.00,8000.00,24
2972,2972,1015354341,Comics,2012-04-30,2012-03-31,failed,136.00,1000.00,30
2973,2973,1015357412,Film & Video,2012-09-23,2012-08-24,failed,255.50,18000.00,30
2974,2974,1015357640,Film & Video,2013-06-15,2013-05-14,failed,75.00,2500.00,32
2975,2975,1015362799,Design,2013-10-13,2013-09-13,canceled,2449.00,6000.00,30
2976,2976,1015365700,Design,2016-05-19,2016-04-19,failed,32.53,280.47,30
2977,2977,1015372493,Dance,2015-01-16,2014-12-17,successful,1935.20,1506.44,30
2978,2978,1015375165,Film & Video,2013-10-10,2013-09-09,successful,55223.00,50000.00,31
2979,2979,1015381354,Technology,2015-09-05,2015-08-06,canceled,0.00,1200.00,30
2980,2980,1015385304,Film & Video,2014-10-03,2014-09-03,failed,1.00,50000.00,30
2981,2981,1015391940,Film & Video,2012-06-30,2012-05-31,successful,6510.00,6500.00,30
2982,2982,1015409774,Games,2018-01-28,2017-12-29,live,2445.00,15000.00,30
2983,2983,1015413468,Art,2013-03-19,2013-02-25,successful,4570.06,3900.00,22
2984,2984,1015417252,Comics,2017-10-02,2017-09-21,successful,4208.00,1000.00,11
2985,2985,1015427142,Fashion,2014-03-15,2014-02-13,failed,90.00,5000.00,30
2986,2986,1015427647,Film & Video,2014-07-02,2014-06-02,failed,0.00,40000.00,30
2987,2987,1015429625,Technology,2016-03-16,2016-02-16,failed,2.00,75000.00,29
2988,2988,1015431039,Publishing,2012-03-13,2012-02-12,failed,0.00,5000.00,30
2989,2989,1015437901,Music,2012-08-21,2012-07-17,successful,10412.00,10000.00,35
2990,2990,1015442322,Theater,2014-03-16,2014-01-15,failed,610.00,2500.00,60
2991,2991,1015448692,Art,2015-10-16,2015-09-16,successful,18964.42,8520.02,30
2992,2992,1015459707,Publishing,2012-06-07,2012-05-08,failed,200.00,1500.00,30
2993,2993,1015466274,Film & Video,2015-09-01,2015-07-07,failed,0.00,5568982.99,56
2994,2994,1015471596,Art,2017-12-13,2017-10-14,canceled,0.00,1206.81,60
2995,2995,1015474687,Film & Video,2014-04-09,2014-03-10,failed,230.00,2200.00,30
2996,2996,10154884,Music,2012-07-16,2012-06-02,successful,8792.00,8000.00,44
2997,2997,1015500034,Technology,2015-08-23,2015-06-24,failed,165.64,4507.19,60
2998,2998,101550119,Publishing,2012-06-28,2012-05-29,failed,150.00,5000.00,30
2999,2999,1015511629,Music,2014-03-29,2014-01-28,failed,104.40,1657.19,60

In [27]:
len(df)

3000

In [28]:
df

,Unnamed: 0,ID,categoryUnnamed,deadline,launched,state,pledged,goal,duration
0,0,1000002330,Publishing,2015-10-09,2015-08-11,failed,0.00,1533.95,59
1,1,1000003930,Film & Video,2017-11-01,2017-09-02,failed,2421.00,30000.00,60
2,2,1000004038,Film & Video,2013-02-26,2013-01-12,failed,220.00,45000.00,45
3,3,1000007540,Music,2012-04-16,2012-03-17,failed,1.00,5000.00,30
4,4,1000011046,Film & Video,2015-08-29,2015-07-04,canceled,1283.00,19500.00,56
5,5,1000014025,Food,2016-04-01,2016-02-26,successful,52375.00,50000.00,35
6,6,1000023410,Food,2014-12-21,2014-12-01,successful,1205.00,1000.00,20
7,7,1000030581,Food,2016-03-17,2016-02-01,failed,453.00,25000.00,45
8,8,1000034518,Design,2014-05-29,2014-04-24,canceled,8233.00,125000.00,35
9,9,100004195,Film & Video,2014-08-10,2014-07-11,canceled,6240.57,65000.00,30
10,10,100004721,Publishing,2013-10-09,2013-09-09,failed,0.00,2406.39,30
11,11,100005484,Music,2013-04-08,2013-03-09,successful,12700.00,12500.00,30
12,12,1000055792,Crafts,2014-10-02,2014-09-02,failed,0.00,5000.00,30
13,13,1000056157,Games,2016-03-25,2016-02-09,failed,0.00,200000.00,45
14,14,1000057089,Games,2017-05-03,2017-04-05,successful,121857.33,6469.73,28
15,15,1000064368,Design,2015-02-28,2015-01-29,failed,664.00,2500.00,30
16,16,1000064918,Comics,2014-11-08,2014-10-09,failed,395.00,1500.00,30
17,17,1000068480,Publishing,2015-05-10,2015-04-10,failed,789.00,3000.00,30
18,18,1000070642,Music,2012-08-17,2012-08-02,successful,250.00,250.00,15
19,19,1000071625,Food,2012-06-02,2012-05-03,failed,1781.00,5000.00,30
20,20,1000072011,Fashion,2013-12-30,2013-11-25,successful,34268.00,20000.00,35
21,21,1000081649,Fashion,2017-09-07,2017-08-08,failed,0.81,2026.10,30
22,22,1000082254,Theater,2014-06-15,2014-05-16,failed,650.00,3500.00,30
23,23,1000087442,Food,2015-02-25,2015-01-26,failed,6.29,65.55,30
24,24,1000091520,Comics,2014-11-12,2014-10-23,successful,701.66,175.00,20
25,25,1000102741,Music,2011-01-06,2010-12-07,successful,15827.00,10000.00,30
26,26,1000103948,Crafts,2016-01-05,2015-12-06,failed,0.00,17489.65,30
27,27,1000104688,Film & Video,2014-12-14,2014-11-14,successful,42174.03,15313.04,30
28,28,1000104953,Comics,2016-01-28,2015-12-29,successful,160.60,142.91,30
29,29,100011318,Film & Video,2017-05-03,2017-04-03,successful,57577.31,50000.00,30
...,...,...,...,...,...,...,...,...,...
2970,2970,1015341816,Film & Video,2014-05-09,2014-04-09,successful,16276.00,15000.00,30
2971,2971,1015351174,Design,2017-01-02,2016-12-09,canceled,3426.00,8000.00,24
2972,2972,1015354341,Comics,2012-04-30,2012-03-31,failed,136.00,1000.00,30
2973,2973,1015357412,Film & Video,2012-09-23,2012-08-24,failed,255.50,18000.00,30
2974,2974,1015357640,Film & Video,2013-06-15,2013-05-14,failed,75.00,2500.00,32
2975,2975,1015362799,Design,2013-10-13,2013-09-13,canceled,2449.00,6000.00,30
2976,2976,1015365700,Design,2016-05-19,2016-04-19,failed,32.53,280.47,30
2977,2977,1015372493,Dance,2015-01-16,2014-12-17,successful,1935.20,1506.44,30
2978,2978,1015375165,Film & Video,2013-10-10,2013-09-09,successful,55223.00,50000.00,31
2979,2979,1015381354,Technology,2015-09-05,2015-08-06,canceled,0.00,1200.00,30
2980,2980,1015385304,Film & Video,2014-10-03,2014-09-03,failed,1.00,50000.00,30
2981,2981,1015391940,Film & Video,2012-06-30,2012-05-31,successful,6510.00,6500.00,30
2982,2982,1015409774,Games,2018-01-28,2017-12-29,live,2445.00,15000.00,30
2983,2983,1015413468,Art,2013-03-19,2013-02-25,successful,4570.06,3900.00,22
2984,2984,1015417252,Comics,2017-10-02,2017-09-21,successful,4208.00,1000.00,11
2985,2985,1015427142,Fashion,2014-03-15,2014-02-13,failed,90.00,5000.00,30
2986,2986,1015427647,Film & Video,2014-07-02,2014-06-02,failed,0.00,40000.00,30
2987,2987,1015429625,Technology,2016-03-16,2016-02-16,failed,2.00,75000.00,29
2988,2988,1015431039,Publishing,2012-03-13,2012-02-12,failed,0.00,5000.00,30
2989,2989,1015437901,Music,2012-08-21,2012-07-17,successful,10412.00,10000.00,35
2990,2990,1015442322,Theater,2014-03-16,2014-01-15,failed,610.00,2500.00,60
2991,2991,1015448692,Art,2015-10-16,2015-09-16,successful,18964.42,8520.02,30
2992,2992,1015459707,Publishing,2012-06-07,2012-05-08,failed,200.00,1500.00,30
2993,2993,1015466274,Film & Video,2015-09-01,2015-07-07,failed,0.00,5568982.99,56
2994,2994,1015471596,Art,2017-12-13,2017-10-14,canceled,0.00,1206.81,60
2995,2995,1015474687,Film & Video,2014-04-09,2014-03-10,failed,230.00,2200.00,30
2996,2996,10154884,Music,2012-07-16,2012-06-02,successful,8792.00,8000.00,44
2997,2997,1015500034,Technology,2015-08-23,2015-06-24,failed,165.64,4507.19,60
2998,2998,101550119,Publishing,2012-06-28,2012-05-29,failed,150.00,5000.00,30
2999,2999,1015511629,Music,2014-03-29,2014-01-28,failed,104.40,1657.19,60

In [29]:
df['duration'].value_counts()

30       1344
60        251
45        165
31        106
40         83
35         82
32         51
29         50
15         48
21         48
25         44
33         44
20         43
28         38
14         35
36         29
50         28
27         27
22         26
37         25
34         25
38         23
17         20
24         20
43         19
59         17
16         17
7          17
18         16
44         16
         ...
13          8
51          8
90          8
48          7
56          7
9           6
55          6
47          6
6           6
12          6
58          5
61          5
11          5
54          5
57          4
91          4
53          4
83          3
52          3
62          3
5           3
66          3
1           2
71          2
64          1
73          1
87          1
14867       1
89          1
3           1
Name: duration, Length: 70, dtype: int64